[[redirects]]
  from = "/api/*"
  to = "https://nodejs212.dszcbaross.edu.hu/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/uploads/*"
  to = "https://nodejs212.dszcbaross.edu.hu/uploads/:splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}